
server:
  port: 8086
  
spring:
 security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-83683824.okta.com/oauth2/default
      client:
        registration:
         internal-client:
          provider: okta
          authorization-grant-type: client_credentials
          scope: internal
          client-id: 0oa7y6vb382VnNeg25d7
          client-secret: 01CD7i-maJdT28Bgoxnr2ZPIgREmbEx358QMjZvi
        provider:
         okta:
           issuer-uri: https://dev-83683824.okta.com/oauth2/default
           
                    
                 
          

 datasource:
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: root
  url: jdbc:mysql://${DB_Host:localhost}:3306/orderdb
  
    
 jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
 application:
    name: ORDER-SERVICE 
 config:
    import:
    CONFIG_SERVICE: http://localhost:9296
      enabled=false


resilience4j:
  circuitbreaker:
    instances:
      external:
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 5
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 5s
       permitted-number-of-calls-in-half-open-state: 3 
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED
        
        

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}             
                  
         
                  
               
 
  
    
    
  